name: CI/CD for Letter Service

on:
  push:
    branches: [main]

env:
  IMAGE_NAME: letter-service

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./letter-service
        file: ./letter-service/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/letter-service:latest
        build-args: |
          DB_NAME=${{ secrets.LETTER_DB_NAME }}
          DB_USER=${{ secrets.LETTER_DB_USERNAME }}
          DB_PASSWORD=${{ secrets.LETTER_DB_PASSWORD }}
          DB_HOST=${{ secrets.LETTER_DB_HOST }}

    - name: Set up gcloud
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Configure GKE credentials
      run: |
        gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER }} --zone ${{ secrets.GKE_ZONE }}

    - name: Deploy to GKE
      run: |
        kubectl apply -f ./k8s/letter/deployment.yaml
        kubectl apply -f ./k8s/letter/service.yaml
